---

homebrew_taps:
  - caskroom/cask
  - caskroom/versions

cask_apps:
  firefox: {}
  java8: {}

homebrew_apps:
  bash-completion: {}
  brew-cask-completion: {}
  git: {}
  gnupg: {}
  grep: {}
  lastpass-cli:
    install_options: 'with-pinentry'
  pipenv: {}
  pyenv: {}
  python: {}
  python@2: {}

git_user: Milo Minderbinder
git_email: minderbinder.enterprises@gmail.com
